-- ============================================================================
-- AVISO (Events Query API)
-- Este script es un BORRADOR / variante de DDL: no incluye CATEGORIAS ni
-- EVENTO_CATEGORIAS, y EVENTOS_MASTER usa Categorias_Array/Tags_IA_Array en
-- lugar de Tags_ES, Tags_CAT y embeddings del esquema final.
--
-- Para recrear la BD que usa la API en Railway o local, usa en su lugar:
--   SQL/SCHEMA_SQL_FINAL.sql   (o scripts/schema.sql)
-- y rellena datos con:  python scripts/generate_fake_data.py
-- Ver: docs/DEPLOYMENT.md
-- ============================================================================

CREATE TABLE `CIUDADES` (
  `ID_Ciudad` INT PRIMARY KEY AUTO_INCREMENT,
  `Nombre` VARCHAR(255) UNIQUE NOT NULL,
  `Provincia` VARCHAR(255),
  `Latitud` DECIMAL(10,8),
  `Longitud` DECIMAL(11,8)
);

CREATE TABLE `CODIGOS_POSTALES` (
  `CP` VARCHAR(5) PRIMARY KEY,
  `ID_Ciudad` INT,
  `Latitud` DECIMAL(10,8) NOT NULL,
  `Longitud` DECIMAL(11,8) NOT NULL,
  `Barrio_Distrito` VARCHAR(255)
);

CREATE TABLE `PERFIL_USUARIO` (
  `ID_Usuario` INT PRIMARY KEY AUTO_INCREMENT,
  `Nombre_Usuario` VARCHAR(255),
  `CP_Origen` VARCHAR(5) NOT NULL,
  `Radio_Busqueda_KM` INT NOT NULL DEFAULT 15
);

CREATE TABLE `MAPEO_REDES_POBLACION` (
  `ID_Mapeo_Social` INT PRIMARY KEY AUTO_INCREMENT,
  `ID_Ciudad` INT NOT NULL,
  `Plataforma` ENUM ('INSTAGRAM', 'FACEBOOK', 'X_TWITTER', 'TIKTOK') NOT NULL,
  `Hashtag_Principal` VARCHAR(255),
  `Handle_Oficial` VARCHAR(255)
);

CREATE TABLE `MAPEO_AGREGADORES_POBLACION` (
  `ID_Mapeo_Agregador` INT PRIMARY KEY AUTO_INCREMENT,
  `ID_Ciudad` INT NOT NULL,
  `Nombre_Agregador` VARCHAR(255) NOT NULL,
  `URL_Base_Busqueda` VARCHAR(2048) NOT NULL
);

CREATE TABLE `FUENTES_FAMILIA` (
  `ID_Familia` VARCHAR(255) PRIMARY KEY,
  `ID_Ciudad` INT NOT NULL,
  `Nombre_Entidad` VARCHAR(255) NOT NULL,
  `URL_Raiz_Global` VARCHAR(2048) NOT NULL
);

CREATE TABLE `URLS_POSTS_REDES` (
  `ID_Post_URL` INT PRIMARY KEY AUTO_INCREMENT,
  `ID_Ciudad` INT NOT NULL,
  `Plataforma` ENUM ('INSTAGRAM', 'FACEBOOK', 'X_TWITTER', 'TIKTOK') NOT NULL,
  `URL_Post` VARCHAR(2048) NOT NULL,
  `Estado` ENUM ('PENDIENTE', 'OK', 'ERROR', 'PAUSADO') NOT NULL DEFAULT 'PENDIENTE',
  `Intentos` INT NOT NULL DEFAULT 0,
  `Ultima_Ejecucion` DATETIME,
  `Ultimo_Error` TEXT
);

CREATE TABLE `SCRAPING_TARGETS` (
  `ID_Target` INT PRIMARY KEY AUTO_INCREMENT,
  `ID_Ciudad` INT NOT NULL,
  `Tipo_Target` ENUM ('AGREGADOR', 'FUENTE_OFICIAL', 'RED_SOCIAL_POST') NOT NULL,
  `Plataforma` ENUM ('INSTAGRAM', 'FACEBOOK', 'X_TWITTER', 'TIKTOK'),
  `URL_Target` VARCHAR(2048),
  `Query_Target` VARCHAR(255),
  `Origen_Tabla` VARCHAR(64) NOT NULL,
  `Origen_ID` VARCHAR(255) NOT NULL,
  `Estado` ENUM ('PENDIENTE', 'PROCESANDO', 'OK', 'ERROR', 'PAUSADO') NOT NULL DEFAULT 'PENDIENTE',
  `Frecuencia_Horas` INT NOT NULL DEFAULT 24,
  `Next_Run_At` DATETIME,
  `Last_Run_At` DATETIME,
  `Intentos` INT NOT NULL DEFAULT 0,
  `Last_Error` TEXT,
  `Http_ETag` VARCHAR(255),
  `Http_LastModified` VARCHAR(255),
  `Content_Fingerprint` CHAR(64),
  `Last_Changed_At` DATETIME
);

CREATE TABLE `EVENTOS_MASTER` (
  `ID_Unico_Evento` CHAR(64) PRIMARY KEY,
  `Metodo_Ingesta` ENUM ('SCRAPING', 'MANUAL') NOT NULL,
  `ID_Usuario_Carga` VARCHAR(255) NOT NULL COMMENT 'SYSTEM para IA o ID_USER para humanos',
  `Fuente_ID` ENUM ('URL_ESTRUCTURAL', 'SOCIAL_VISUAL', 'SOCIAL_SEMANTICA') NOT NULL,
  `Fuente_URL_Original` VARCHAR(2048) COMMENT 'URL canónica (1). Otras URLs se registran en auditoría.',
  `Estado` ENUM ('ACTIVO', 'CANCELADO', 'APLAZADO') NOT NULL DEFAULT 'ACTIVO',
  `Fecha_Creacion` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `ID_Ciudad` INT,
  `CP_Evento` VARCHAR(5) NOT NULL,
  `Poblacion_Nombre` VARCHAR(255) NOT NULL,
  `Lugar_Nombre` VARCHAR(255) NOT NULL,
  `Direccion_Fisica` VARCHAR(255),
  `Coordenadas_JSON` JSON COMMENT '{"lat": float, "lng": float}',
  `ID_Familia` VARCHAR(255),
  `Tipo_Organizador` ENUM ('PUBLICO', 'PRIVADO', 'ASOCIACION'),
  `Organizador_Nombre` VARCHAR(255),
  `Organizador_Web` VARCHAR(2048),
  `Es_Patrocinado` TINYINT(1) NOT NULL DEFAULT 0,
  `Idioma_Origen` CHAR(2) NOT NULL COMMENT 'ca o es',
  `Titulo_CAT` VARCHAR(255) NOT NULL,
  `Titulo_ES` VARCHAR(255) NOT NULL,
  `Desc_Larga_CAT` TEXT,
  `Desc_Larga_ES` TEXT,
  `Categorias_Array` JSON,
  `Tags_IA_Array` JSON,
  `Es_Gratuito` TINYINT(1) NOT NULL,
  `Precio_Euros` DECIMAL(10,2),
  `Requiere_Inscripcion` TINYINT(1) NOT NULL,
  `Aforo_Maximo` INT,
  `Plazas_Disponibles` INT,
  `Link_Entradas_Inscripcion` VARCHAR(2048),
  `Imagen_Principal_URL` VARCHAR(2048)
);

CREATE TABLE `EVENTO_HORARIOS` (
  `ID_Horario` INT PRIMARY KEY AUTO_INCREMENT,
  `ID_Unico_Evento` CHAR(64) NOT NULL,
  `Fecha_Inicio` DATE NOT NULL,
  `Fecha_Fin` DATE COMMENT 'Para rangos o eventos recurrentes',
  `Hora_Inicio` TIME,
  `Hora_Fin` TIME,
  `Es_Recurrente` TINYINT(1) NOT NULL DEFAULT 0,
  `Recurrencia_JSON` JSON COMMENT 'Debe seguir el esquema de documentación (ReadMe).',
  `Horario_Texto_ES` VARCHAR(255) COMMENT 'Texto legible: "De 08:00 a 10:00"'
);

CREATE TABLE `BINARIOS_STORAGE` (
  `ID_Binario` INT PRIMARY KEY AUTO_INCREMENT,
  `ID_Unico_Evento` CHAR(64) NOT NULL,
  `Nombre_Archivo` VARCHAR(255) NOT NULL,
  `Tipo_Archivo` ENUM ('PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'DOCX') NOT NULL,
  `URL_Almacenamiento_Nube` VARCHAR(2048) NOT NULL,
  `Checksum_SHA256` CHAR(64),
  `Fecha_Sincronizacion` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE `AUDITORIA_SCRAPING` (
  `ID_Auditoria` INT PRIMARY KEY AUTO_INCREMENT,
  `ID_Unico_Evento` CHAR(64),
  `URL_Procesada` VARCHAR(2048),
  `Metodo_Usado` VARCHAR(255) COMMENT 'Para debuggear el Fuente_ID / parser aplicado',
  `Resultado` ENUM ('OK', 'WARNING', 'ERROR') NOT NULL DEFAULT 'OK',
  `Detalle` TEXT,
  `Texto_Bruto_Caption` TEXT,
  `Texto_Bruto_OCR` TEXT COMMENT 'Texto "sucio" leído de la imagen',
  `Payload_Extra` JSON,
  `Fecha_Ejecucion` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE UNIQUE INDEX `UQ_POST_URL` ON `URLS_POSTS_REDES` (`URL_Post`);

CREATE UNIQUE INDEX `UQ_TARGET_ORIGEN` ON `SCRAPING_TARGETS` (`Origen_Tabla`, `Origen_ID`);

CREATE INDEX `IDX_TARGET_NEXT` ON `SCRAPING_TARGETS` (`Estado`, `Next_Run_At`);

CREATE INDEX `IDX_EVENTO_CP` ON `EVENTOS_MASTER` (`CP_Evento`);

CREATE INDEX `IDX_EVENTO_CIUDAD` ON `EVENTOS_MASTER` (`ID_Ciudad`);

CREATE INDEX `IDX_BINARIO_EVENTO` ON `BINARIOS_STORAGE` (`ID_Unico_Evento`);

CREATE INDEX `IDX_AUDIT_EVENTO` ON `AUDITORIA_SCRAPING` (`ID_Unico_Evento`);

ALTER TABLE `CODIGOS_POSTALES` ADD CONSTRAINT `FK_CP_CIUDAD` FOREIGN KEY (`ID_Ciudad`) REFERENCES `CIUDADES` (`ID_Ciudad`);

ALTER TABLE `PERFIL_USUARIO` ADD CONSTRAINT `FK_USER_CP` FOREIGN KEY (`CP_Origen`) REFERENCES `CODIGOS_POSTALES` (`CP`);

ALTER TABLE `MAPEO_REDES_POBLACION` ADD CONSTRAINT `FK_REDES_CIUDAD` FOREIGN KEY (`ID_Ciudad`) REFERENCES `CIUDADES` (`ID_Ciudad`);

ALTER TABLE `MAPEO_AGREGADORES_POBLACION` ADD CONSTRAINT `FK_AGREGADOR_CIUDAD` FOREIGN KEY (`ID_Ciudad`) REFERENCES `CIUDADES` (`ID_Ciudad`);

ALTER TABLE `FUENTES_FAMILIA` ADD CONSTRAINT `FK_FUENTE_CIUDAD` FOREIGN KEY (`ID_Ciudad`) REFERENCES `CIUDADES` (`ID_Ciudad`);

ALTER TABLE `URLS_POSTS_REDES` ADD CONSTRAINT `FK_POST_CIUDAD` FOREIGN KEY (`ID_Ciudad`) REFERENCES `CIUDADES` (`ID_Ciudad`);

ALTER TABLE `SCRAPING_TARGETS` ADD CONSTRAINT `FK_TARGET_CIUDAD` FOREIGN KEY (`ID_Ciudad`) REFERENCES `CIUDADES` (`ID_Ciudad`);

ALTER TABLE `EVENTOS_MASTER` ADD CONSTRAINT `FK_EVENTO_CP` FOREIGN KEY (`CP_Evento`) REFERENCES `CODIGOS_POSTALES` (`CP`);

ALTER TABLE `EVENTOS_MASTER` ADD CONSTRAINT `FK_EVENTO_CIUDAD` FOREIGN KEY (`ID_Ciudad`) REFERENCES `CIUDADES` (`ID_Ciudad`);

ALTER TABLE `EVENTOS_MASTER` ADD CONSTRAINT `FK_EVENTO_FAMILIA` FOREIGN KEY (`ID_Familia`) REFERENCES `FUENTES_FAMILIA` (`ID_Familia`);

ALTER TABLE `EVENTO_HORARIOS` ADD CONSTRAINT `FK_HORARIO_EVENTO` FOREIGN KEY (`ID_Unico_Evento`) REFERENCES `EVENTOS_MASTER` (`ID_Unico_Evento`);

ALTER TABLE `BINARIOS_STORAGE` ADD CONSTRAINT `FK_BINARIO_EVENTO` FOREIGN KEY (`ID_Unico_Evento`) REFERENCES `EVENTOS_MASTER` (`ID_Unico_Evento`);

ALTER TABLE `AUDITORIA_SCRAPING` ADD CONSTRAINT `FK_AUDIT_EVENTO` FOREIGN KEY (`ID_Unico_Evento`) REFERENCES `EVENTOS_MASTER` (`ID_Unico_Evento`);
